local util = require('customize_fps.util')

local Setting = {
    Settings = {
        Enabled = true,
        FPS = {
            Default = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = false,
            },
            ['Great Sword'] = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = true,
                Default = true,
            },
            ['Long Sword'] = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = true,
                Default = true,
            },
            ['Sword & Shield'] = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = true,
                Default = true,
            },
            ['Dual Blades'] = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = true,
                Default = true,
            },
            Hammer = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = true,
                Default = true,
            },
            ['Hunting Horn'] = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = true,
                Default = true,
            },
            Lance = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = true,
                Default = true,
            },
            Gunlance = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = false,
                Default = false,
            },
            ['Switch Axe'] = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = true,
                Default = true,
            },
            ['Charge Blade'] = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = true,
                Default = true,
            },
            ['Insect Glaive'] = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = true,
                Default = true,
            },
            ['Light Bowgun'] = {
                Ammo = {
                    Normal = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Pierce = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Spread = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Slicing = {
                        MaxFPS = 75,
                        CappedFPS = true,
                        FrameGeneration = util.FrameGeneration.On,
                        Unchanged = false,
                        Default = false,
                    },
                    Sticky = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Cluster = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Wyvern = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Poison = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Paralysis = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Sleep = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Flaming = {
                        MaxFPS = 35,
                        CappedFPS = true,
                        FrameGeneration = util.FrameGeneration.On,
                        Unchanged = false,
                        Default = false,
                    },
                    Water = {
                        MaxFPS = 35,
                        CappedFPS = true,
                        FrameGeneration = util.FrameGeneration.On,
                        Unchanged = false,
                        Default = false,
                    },
                    Thunder = {
                        MaxFPS = 35,
                        CappedFPS = true,
                        FrameGeneration = util.FrameGeneration.On,
                        Unchanged = false,
                        Default = false,
                    },
                    Freeze = {
                        MaxFPS = 35,
                        CappedFPS = true,
                        FrameGeneration = util.FrameGeneration.On,
                        Unchanged = false,
                        Default = false,
                    },
                    Dragon = {
                        MaxFPS = 35,
                        CappedFPS = true,
                        FrameGeneration = util.FrameGeneration.On,
                        Unchanged = false,
                        Default = false,
                    },
                    Recover = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Demon = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Armor = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Exhaust = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Tranq = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                },
            },
            ['Heavy Bowgun'] = {
                Ammo = {
                    Normal = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Pierce = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Spread = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Slicing = {
                        MaxFPS = 75,
                        CappedFPS = true,
                        FrameGeneration = util.FrameGeneration.On,
                        Unchanged = false,
                        Default = false,
                    },
                    Sticky = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Cluster = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Wyvern = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Poison = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Paralysis = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Sleep = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Flaming = {
                        MaxFPS = 35,
                        CappedFPS = true,
                        FrameGeneration = util.FrameGeneration.On,
                        Unchanged = false,
                        Default = false,
                    },
                    Water = {
                        MaxFPS = 35,
                        CappedFPS = true,
                        FrameGeneration = util.FrameGeneration.On,
                        Unchanged = false,
                        Default = false,
                    },
                    Thunder = {
                        MaxFPS = 35,
                        CappedFPS = true,
                        FrameGeneration = util.FrameGeneration.On,
                        Unchanged = false,
                        Default = false,
                    },
                    Freeze = {
                        MaxFPS = 35,
                        CappedFPS = true,
                        FrameGeneration = util.FrameGeneration.On,
                        Unchanged = false,
                        Default = false,
                    },
                    Dragon = {
                        MaxFPS = 35,
                        CappedFPS = true,
                        FrameGeneration = util.FrameGeneration.On,
                        Unchanged = false,
                        Default = false,
                    },
                    Recover = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Demon = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Armor = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Exhaust = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                    Tranq = {
                        MaxFPS = 60,
                        CappedFPS = false,
                        FrameGeneration = util.FrameGeneration.Unchanged,
                        Unchanged = true,
                        Default = true,
                    },
                },
            },
            Bow = {
                MaxFPS = 60,
                CappedFPS = false,
                FrameGeneration = util.FrameGeneration.Unchanged,
                Unchanged = true,
                Default = true,
            },
        },
    },
}

function Setting.SaveSettings()
	json.dump_file('customize_fps.json', Setting.Settings)
end

function Setting.LoadSettings()
	local loadedSettings = json.load_file('customize_fps.json')
	if loadedSettings then
        for k, v in pairs(loadedSettings) do
            Setting.Settings[k] = v
        end
	end
end

return Setting
