Util = {
  SettingOrder = {
    'Default',
    'Great Sword',
    'Long Sword',
    'Sword & Shield',
    'Dual Blades',
    'Hammer',
    'Hunting Horn',
    'Lance',
    'Gunlance',
    'Switch Axe',
    'Charge Blade',
    'Insect Glaive',
    'Light Bowgun',
    'Heavy Bowgun',
    'Bow',
  },
  AmmoOrder = {
    'Normal',
    'Pierce',
    'Spread',
    'Slicing',
    'Sticky',
    'Cluster',
    'Wyvern',
    'Poison',
    'Paralysis',
    'Sleep',
    'Flaming',
    'Water',
    'Thunder',
    'Freeze',
    'Dragon',
    'Recover',
    'Demon',
    'Armor',
    'Exhaust',
    'Tranq',
  },
  FrameGeneration = {
    Off = 1,
    On = 2,
    Unchanged = 3,
  },
  WeaponType = {
    [0] = 'Great Sword',
    [1] = 'Sword & Shield',
    [2] = 'Dual Blades',
    [3] = 'Long Sword',
    [4] = 'Hammer',
    [5] = 'Hunting Horn',
    [6] = 'Lance',
    [7] = 'Gunlance',
    [8] = 'Switch Axe',
    [9] = 'Charge Blade',
    [10] = 'Insect Glaive',
    [11] = 'Bow',
    [12] = 'Heavy Bowgun',
    [13] = 'Light Bowgun',
  },
  ShellType = {
    [0] = 'Normal',
    [1] = 'Pierce',
    [2] = 'Spread',
    [3] = 'Sticky',
    [4] = 'Cluster',
    [5] = 'Slicing',
    [6] = 'Wyvern',
    [7] = 'Flaming',
    [8] = 'Water',
    [9] = 'Thunder',
    [10] = 'Freeze',
    [11] = 'Dragon',
    [12] = 'Poison',
    [13] = 'Paralysis',
    [14] = 'Sleep',
    [15] = 'Demon',
    [16] = 'Armor',
    [17] = 'Recover',
    [18] = 'Exhaust',
    [19] = 'Tranq',
  }
}

return Util